version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Budget-App
    ports:
      - "3000:3000"
    depends_on:
      - db
